// demo-vue/src/App.vue
<template>
  <se-app>
      <se-header v-bind:app-title="appInformation"></se-header>
      <se-navbar color="primary">
        <nav slot="start">Tenant: <a class="dropdown"> test </a></nav>
        <nav><a class="active">Home</a> <a>Components</a> <a>Icons</a></nav>
      </se-navbar>
      <se-widget-container>
        <se-widget>
          <se-widget-header>Filter</se-widget-header>
          <se-widget-content>
              <div class="mycoolstyle">my content</div>
              <ul>
                ...
              </ul>
          </se-widget-content>
          <se-widget-footer>
            <se-button>Apply</se-button>
          </se-widget-footer>
        </se-widget>
      </se-widget-container>
    </se-app>
</template>

<script>
export default {
  name: 'app',
  data() {
    return {
      appInformation: "Test Advisor"
    };
  }
};
</script>
<style>
  .mycoolstyle {
    color: red;
  }
   .flex {
      flex: 1
    }
    .d-flex {
      display: flex;
    }
</style>

// demo-react/src/App.js
import React, { Component } from 'react';
import Widget from './widget';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      rating: 1,
    };
  }

  componentDidMount() {
    this.ngElement = this.refs.header;
    this.ngElement.appTitle = "Test Advisor";
    // we need to bind the event listener this way, since we can't get the custom event past react's synthetic event system
    // more on this at: https://github.com/facebook/react/issues/7901
    // this.ngElement.addEventListener('ratingChange', data => {
    //   this.setState({ rating: data.detail });
    // });
  }

  setMaxRating = () => {
    this.setState({ rating: 2 });
  };

  render() {
    const filters = [
      {
          'name': 'react filter 1'
      },
      {
          'name': 'reactFilet 2',
      },
      {
          'name': 'Filter 3 from react',
      },
      {
          'name': 'Last filter!'
      },
      {
          'name': 'Last filter!'
      }
    ];
    const rows = filters.map((row, index) => {
        return (
           <Widget name={row.name}/>
        );
    });
    return (
      <se-app>
        <se-header ref="header" appTitle="title"></se-header>
        <se-navbar color="primary">
          <nav slot="start">
            Tenant: <a class="dropdown"> test </a>
          </nav>
          <nav>
            <a class="active">Home</a> <a>Components</a> <a>Icons</a>
          </nav>
        </se-navbar>

        <se-widget-container>
          {rows}
        </se-widget-container>
      </se-app>
    );
  }
}

export default App;
