// src-react/src/components/App.react.js
import React, { Component } from "react";
import PropTypes from "prop-types";

export default class App extends Component {
	render() {
		const { option, children } = this.props;
		return (
			<se-app option={option} ref={this._handleRef}>{children}</se-app>
		);
	}
}

App.defaultProps = {};

App.propTypes = {
  /**
   * The children of this component
   */
  children: PropTypes.node,
  /**
   * Define the type of application. updating the option will impact the font used.
   * - `technical`: For technical application (i.e. EcoStuxure), the font used will be `Nunito`.
   * - `website`: For `se.com` application, the font used will be `Arial Rounded`.
   */
  option: PropTypes."technical" | "website"
};

// src-core/src/components/app/app.tsx
import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'se-app',
  styleUrl: 'app.scss',
  shadow: false
})
export class AppComponent {

  /**
   * Define the type of application. updating the option will impact the font used.
   * - `technical`: For technical application (i.e. EcoStuxure), the font used will be `Nunito`.
   * - `website`: For `se.com` application, the font used will be `Arial Rounded`.
   */
  @Prop() option: 'technical' | 'website' = 'technical';

  render() {
    return <div class={['se-app-body', this.option === "website" ? 'se-font-website' : 'se-font-technical'].join(' ')}><slot></slot></div>;
  }
}
