// apps/react-demo/src/app/app.tsx
import React, { Component } from 'react';
import { Route, Switch, BrowserRouter } from "react-router-dom"
import ShellLayout from './layouts/shell';
import DefaultLayout from './layouts/default';
import { SeApp } from '@se/web-ui-react';
import Home from './pages/home';
import Dashboard from './pages/dashboard';
import Icons from './pages/icons';
import NoPage from './pages/404';
import './styles.scss';

const AppRoute = ({ component: Component, layout: Layout, ...rest }) => (
  <Route {...rest} render={props => (
    <Layout>
      <Component {...props} />
    </Layout>
  )} />
)


class App extends Component {
  render() {
    return (
      <SeApp>
        <BrowserRouter>
          <Switch>
            <AppRoute exact path="/" layout={ShellLayout} component={Home} />
            <AppRoute path="/dashboard" layout={ShellLayout} component={Dashboard} />
            <AppRoute path="/icons" layout={ShellLayout} component={Icons} />
            <AppRoute path="/*" layout={DefaultLayout} component={NoPage} />
          </Switch>
        </BrowserRouter>
      </SeApp>
    );
  }
}

export default App;

// apps/vue-demo/src/App.vue
<template>
  <se-app>
    <component :is="layout">
      <router-view />
    </component>
  </se-app>
</template>

<script>
import { SeApp } from '@se/web-ui-vue';

const defaultLayout = 'default';

export default {
  components: { SeApp },
  computed: {
    layout() {
      return (this.$route.meta.layout || defaultLayout) + '-layout';
    },
  },

  created() {
    // nothing defined here (when this.$route.path is other than "/")
    console.log(this.$route, this.$route.meta.layout);
  },

  updated() {
    // something defined here whatever the this.$route.path
    console.log(this.$route, this.$route.meta.layout);
  },
};
</script>

<style lang="scss">
$se-icon-folder: '~@se/icons/fonts';
@import '~@se/icons/scss/styles';
$se-fonts-path: '~@se/fonts/fonts';
@import '~@se/fonts/scss/styles';
</style>
