// src-react/src/components/Snackbar.react.js
import React, { Component } from "react";
import PropTypes from "prop-types";

export default class Snackbar extends Component {

  componentDidMount() {
    this.switchCmp.addEventListener("didClose", e => this.props.didClose(e));
  }

  componentWillUnmount() {
    this.switchCmp.removeEventListener("didClose", e => this.props.didClose(e));
  }

  _handleRef = component => {
    this.switchCmp = component;
  };

	render() {
		const { canClose, closeText, icon, message, open, type, didClose, children } = this.props;
		return (
			<se-snackbar can-close={canClose} close-text={closeText} icon={icon} message={message} open={open} type={type} ref={this._handleRef}>{children}</se-snackbar>
		);
	}
}

Snackbar.defaultProps = {};

Snackbar.propTypes = {
  /**
   * The children of this component
   */
  children: PropTypes.node,
  /**
   * Displays a "button" to close the snackbar.
   * The default setting is `false`.
   * This will be visible if set to `true`.
   */
  canClose: PropTypes.boolean,
  /**
   * Defines the text you want your "close button" to read.  The default text is `dismiss`.
   */
  closeText: PropTypes.string,
  /**
   * The name of the icon you wish to display.  The default icon is an information circle.
   */
  icon: PropTypes.string,
  /**
   * The content of the message you want the snackbar to display.
   */
  message: PropTypes.string,
  /**
   * Indicates if the snackbar is open.  Set to `false` (closed) by default.
   */
  open: PropTypes.boolean,
  /**
   * Indicates the background color of your snackbar.
   * `success`: green
   * `warning`: orange
   * `error`: red
   * `information`: dark grey, default setting
   */
  type: PropTypes."error" | "information" | "success" | "warning",
  /**
   * Sends information to the parent component when closing the snackbar.
   */
  didClose: PropTypes.function
};

// src/components/snackbar/snackbar.tsx
import { Component, Element, Event, EventEmitter, Prop, Watch } from "@stencil/core";

const SHOW_SNACKBAR = 'show';

@Component({
  tag: "se-snackbar",
  styleUrl: "snackbar.scss",
  shadow: true
})

export class SnackbarComponent {
  /**
   * Indicates the background color of your snackbar.
   * `success`: green
   * `warning`: orange
   * `error`: red
   * `information`: dark grey
   */
  @Prop() type: 'success' | 'error' | 'warning' | 'information' = 'information';
  /**
   * The name of the icon you wish to display.  Optional.
   */
  @Prop() icon: string = 'information_circle';
  /**
   * The content of the message you want the snackbar to display.
   */
  @Prop() message: string;
  /**
   * Display a close "button".
   */
  @Prop() canClose: boolean = true;
  /**
   * Defines the text you want your "close button" to read.
   */
  @Prop() closeText: string = 'dismiss';
  /**
   * Indicates if the snackbar is open.
   */
  @Prop({mutable: true}) open: boolean = false;
  @Watch('open') openDidChange() {
    if (this.open) {
      this.el.classList.add(SHOW_SNACKBAR);
    } else {
      this.el.classList.remove(SHOW_SNACKBAR);
    }
  }
  @Element() el: HTMLElement;
  /**
   * Send information to the parent component when closing the snackbar.
   */
  @Event() didClose: EventEmitter;

  closeSnackbar() {
    this.open = false;
    this.didClose.emit();
  }

  hostData() {
    return {
      class: this.type
    }
  }
  
  render() {
    return [
      <div class="snackbar">
        {this.icon ? <span class="se-icon">{this.icon}</span> : ''}
        <span class="message">{this.message}</span>
        {this.canClose ? <span class="close" onClick={() => this.closeSnackbar()}>{this.closeText}</span> : ''}
      </div>
    ];
  }
}
