// demo-angular/src_web/app/core/shell/shell.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-shell',
  templateUrl: './shell.component.html',
  styleUrls: ['./shell.component.scss']
})
export class ShellComponent {
  constructor() {}
}
<se-app>

  <app-header></app-header>

  <se-navbar color='primary'>
    <nav slot="start">
      Tenant:
      <a class="dropdown">
        test
      </a>
    </nav>
    <nav>
      <a routerLink="/home" routerLinkActive="active">Home</a>
      <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
      <a routerLink="/docs" routerLinkActive="active">Docs</a>
    </nav>
    <nav slot="end">
      <a href="">End</a>
    </nav>
  </se-navbar>
  <se-widget-container>
        <router-outlet></router-outlet>
  </se-widget-container>
</se-app>

// demo-vue/src/layouts/Shell.vue
<template>
  <se-app>
    <se-header app-title="Test Advisor"></se-header>
    <se-navbar color="primary">
      <nav slot="start">Tenant: <a class="dropdown"> test </a></nav>
      <nav>
        <router-link
          :to="{ name: 'home' }"
          @click.native="open = false"
          exact-active-class="active"
        >
          Home
        </router-link>
        <router-link
          :to="{ name: 'dashboard' }"
          @click.native="open = false"
          active-class="active"
        >
          Dashboard
        </router-link>
        <router-link
          :to="{ name: 'icons' }"
          @click.native="open = false"
          active-class="active"
        >
          Icons
        </router-link>
      </nav>
      <nav slot="end">
        <a>End</a>
      </nav>
    </se-navbar>
    <slot />
  </se-app>
</template>
