// demo-react/src/layouts/shell.jsx
import React, {Component} from 'react';
import { NavLink } from 'react-router-dom'

class ShellLayout extends Component {
  render() {
    return (
      <span className="se-app-body">
        <se-header app-title="React Advisor"></se-header>
        <se-tabbar color="primary">
          <nav slot="start">Tenant: <a className="dropdown" href=""> test </a></nav>
          <nav>
            <NavLink to="/" exact={true} activeClassName='active'>Home</NavLink>
            <NavLink to='/dashboard' activeClassName='active'>Dashboard</NavLink>
            <NavLink to='/icons' activeClassName='active'>Icons</NavLink>
          </nav>
          <nav slot="end">
            <a href="">End</a>
          </nav>
        </se-tabbar>
        {this.props.children}
      </span>
    );
  }
}

export default ShellLayout;

// demo-vue/src/layouts/Shell.vue
<template>
  <span class="se-app-body">
    <se-header app-title="Test Advisor"></se-header>
    <se-tabbar color="primary">
      <nav slot="start">Tenant: <a class="dropdown"> test </a></nav>
      <nav>
        <router-link
          :to="{ name: 'home' }"
          @click.native="open = false"
          exact-active-class="active"
        >
          Home
        </router-link>
        <router-link
          :to="{ name: 'dashboard' }"
          @click.native="open = false"
          active-class="active"
        >
          Dashboard
        </router-link>
        <router-link
          :to="{ name: 'icons' }"
          @click.native="open = false"
          active-class="active"
        >
          Icons
        </router-link>
      </nav>
      <nav slot="end">
        <a>End</a>
      </nav>
    </se-tabbar>
    <slot />
  </span>
</template>
