// src-react/src/components/Snackbar.react.js
import React, { Component } from "react";
import PropTypes from "prop-types";

export default class Snackbar extends Component {
  constructor(props) {
    super(props);
    this._handleRef = component => {
      this.switchCmp = component;
    };
  }

  actionClicked(e) {
    this.props.onActionClicked && this.props.onActionClicked(e)
  }
  didClose(e) {
    this.props.onDidClose && this.props.onDidClose(e)
  }

  componentDidMount() {
    this.switchCmp.addEventListener("actionClicked", e => this.actionClicked(e));
    this.switchCmp.addEventListener("didClose", e => this.didClose(e));
  }

  componentWillUnmount() {
    this.switchCmp.removeEventListener("actionClicked", e => this.actionClicked(e));
    this.switchCmp.removeEventListener("didClose", e => this.didClose(e));
  }

	render() {
		const { actionText, canClose, duration, icon, message, open, type, actionClicked, didClose, children } = this.props;
		return (
			<se-snackbar action-text={actionText} can-close={canClose} duration={duration} icon={icon} message={message} open={open} type={type} ref={this._handleRef} >{children}</se-snackbar>
		);
	}
}

Snackbar.defaultProps = {};

Snackbar.propTypes = {
  /**
   * The children of this component
   */
  children: PropTypes.node,
  /**
   * Defines the text you want your custom action button to read.
   */
  actionText: PropTypes.string,
  /**
   * Displays a "button" to close the snackbar.
The default setting is `false`.
This will be visible if set to `true`.
   */
  canClose: PropTypes.bool,
  /**
   * Indicates the duration (in milliseconds) that the snackbar will display on screen before auto-closing, if `canClose` is set to false.
The default setting is 5000.
   */
  duration: PropTypes.number,
  /**
   * The name of the icon you wish to display.  The default icon is an information circle.
   */
  icon: PropTypes.string,
  /**
   * The content of the message you want the snackbar to display.
   */
  message: PropTypes.string,
  /**
   * Indicates if the snackbar is open.  Set to `false` (closed) by default.
   */
  open: PropTypes.bool,
  /**
   * Indicates the background color of your snackbar.
`success`: green
`warning`: orange
`error`: red
`information`: dark grey, default setting
   */
  type: PropTypes.string,
  /**
   * Sends information to the parent component when clicking a custom action button.
   */
  actionClicked: PropTypes.func,
  /**
   * Sends information to the parent component when closing the snackbar.
   */
  didClose: PropTypes.func
};

// libs/core/src/components/snackbar/snackbar.tsx
import { Component, Element, Event, EventEmitter, h, Prop, Watch } from "@stencil/core";
import information_circle from "@se/icons/svg/information_circle.svg";
import action_delete_cross from "@se/icons/svg/action_delete_cross.svg";

const SHOW_SNACKBAR = 'show-snackbar';

@Component({
  tag: "se-snackbar",
  styleUrl: "snackbar.scss",
  shadow: true
})
export class SnackbarComponent {
  @Element() el: HTMLElement;
  /**
   * Indicates the background color of your snackbar.
   * `success`: green
   * `warning`: orange
   * `error`: red
   * `information`: dark grey, default setting
   */
  @Prop() type: 'success' | 'error' | 'warning' | 'information' = 'information';
  /**
   * The name of the icon you wish to display.  The default icon is an information circle.
   */
  @Prop() icon: string | "none" = 'information_circle';
  /**
   * The content of the message you want the snackbar to display.
   */
  @Prop() message: string;
  /**
   * Displays a "button" to close the snackbar.
   * The default setting is `false`.
   * This will be visible if set to `true`.
   */
  @Prop() canClose = false;
  /**
   * Defines the text you want your custom action button to read.
   */
  @Prop() actionText: string;
  /**
   * Indicates if the snackbar is open.  Set to `false` (closed) by default.
   */
  @Prop({ mutable: true }) open = false;
  @Watch('open') openDidChange() {
    if (this.open) {
      this.el.classList.add(SHOW_SNACKBAR);
      setTimeout(() => {
        if (!this.canClose) {
          this.closeSnackbar();
        }
      }, this.duration);
    }
  }
  /**
   * Indicates the duration (in milliseconds) that the snackbar will display on screen before auto-closing, if `canClose` is set to false.
   * The default setting is 5000.
   */
  @Prop() duration = 5000;
  /**
   * Sends information to the parent component when closing the snackbar.
   */
  @Event() didClose: EventEmitter;
  /**
   * Sends information to the parent component when clicking a custom action button.
   */
  @Event() actionClicked: EventEmitter;

  closeSnackbar() {
    this.open = false;
    this.el.classList.remove(SHOW_SNACKBAR);
    this.didClose.emit();
  }

  submitData() {
    this.actionClicked.emit();
  }

  componentDidLoad() {
    this.openDidChange();
  }

  render() {
    let renderIcon: string | boolean = this.icon === 'information_circle' ? information_circle : this.icon;
    if (this.icon === "none") {
      renderIcon = false;
    }
    return (
      <div class={this.type}>
        <div class="snackbar" role="alert">
          <span class="snackbar-icon" >
            {renderIcon && <se-icon><span innerHTML={renderIcon as string}></span></se-icon>}
            <slot name="icon"></slot>
          </span>
         <span class="message">
           {this.message}
           <slot></slot>
          </span>
          {this.actionText ? <span class="action" onClick={() => this.submitData()}>{this.actionText}</span> : ''}
          {this.canClose ? <span class="close"><se-icon onClick={() => this.closeSnackbar()}><span innerHTML={action_delete_cross}></span></se-icon></span> : ''}
        </div>
      </div>
    )
  }
}
